trigger:
- main

pool:
  name: 'Default'        # usa seu agente self-hosted

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    echo "ğŸ“¦ Instalando dependÃªncias..."
    npm ci
  displayName: 'npm ci'

- script: |
    echo "ğŸš€ Rodando testes E2E com Cypress..."
    npx cypress run --browser chrome
  displayName: 'run e2e tests'
